### ISSUE TITLE
Multiplication and division that produce non-integer values throw an Error

### ISSUE THREAD

**Issue by scotttrinh** [sarahdayan/dinero.js#11]
Simple example:

```js
const example = { amount: 500, currency: 'USD' }

Dinero(example).divide(3) // Throws
Dinero(example).divide(2) // Returns valid Dinero object

Dinero(example).multiply(2.01) // Throws
Dinero(example).multiply(2) // Returns valid Dinero object
```

I assume there should be some intermediate rounding that should be happening, and I'd be happy to write a PR that adds some property-based tests and a rounding solution, but wanted a little bit of direction on precision here.

**Comment by sarahdayan** [comment]
Hi @scotttrinh and thanks for offering to help. This issue was raised in #6 and the intermediate rounding was my first idea as well. A few things to consider:

- This should happen in the `multiply` and `divide` methods, not as a Dinero object is being created.
- The rounding mode to use. It feels like the least biased solution would be to use [Banker's rounding](http://wiki.c2.com/?BankersRounding).
- A note should be added to the docs (for `multiply` and `divide`) so users expect rounding to happen when non-integers results are produced.

Please make sure to check [contributing rules](https://github.com/sarahdayan/dinero.js/blob/master/CONTRIBUTING.md).

**Comment by scotttrinh** [comment]
Are you cool with adding a property-based testing library like [JSVerify](https://github.com/jsverify/jsverify) to aiding in finding edge cases? I'll definitely add specific unit tests as well, but since problem can have some weird edge cases, seems like a good use of property-based tests. If you're unsure, I'll be happy to add them in the PR and we can discuss!

**Comment by sarahdayan** [comment]
@scotttrinh I'm not familiar with property-based testing but from a few reads, it sounds interesting. It would need to be Jest-compatible though (or use Jest directly if it has property-based capabilities).

Let's give it a try in the PR and see!

**Comment by scotttrinh** [comment]
Luckily, JSVerify is really easy to use with most testing platforms and seems to work like a charm with Jest! PR is incoming after writing some more test cases.

**Comment by scotttrinh** [comment]
FWIW, chaining multiple `#multiply`/`#divide` operations starts to get kind of lossy since we're rounding each intermediate `Dinero` amount.

Perhaps we ought to suggest in the documentation that if an amount is going to be multiplied and divided a lot that you get the value first, do your multiplication and division and re-wrap the rounded amount?

**Comment by sarahdayan** [comment]
@scotttrinh Rounding will always lead to losses, so that's to be expected. We could define public rounding rules in a separate module, use one by default following Banker's rounding, and provide the possibility for users to pick another via parameter.

Example:

```
multiply(multiplier, roundingMode = ROUND_HALF_UP) { ... }
```

We of course should still warn in the docs that losses may happen and that rounding modes are available for users to pick depending on their use cases.

**Comment by scotttrinh** [comment]
The lossiness would be a little less if we only rounded the final result rather than each time, which is what I was referring to. Having said that aloud, rounding as you go is probably "more correct" from an accounting standpoint since you wouldn't perform some mix of floating point math and rounding in an accounting situation.

Interesting idea about allowing the user to specify the rounding function. I think that is similar to how decimal.js does it, too. Maybe we keep their rounding mode names and use their rounding function for compatibility? Or, we could hav a default but allow one to optionally provide a rounding function, similar to how `Array.prototype#sort` allows you to specify a sorting function?

I'm open to whatever direction suits your style/aesthetic. As a user, I'd be fine with either way.

**Comment by sarahdayan** [comment]
@scotttrinh I agree, but that's more on the user to make that decision. Whether the user performs one or ten chained `multiply`, this isn't something we have any control over. The only thing we can do is ensure a new object is created with a valid set of parameters, and that it's a valid monetary representation.

Here's what would be my approach so far: create a `round` method in the `calculator` which would round a value to a precision and with a rounding mode (can be a string or a number, doesn't really matter). This would determine which algorithm to use (by default, rounding half values to the even closest integer).

**Comment by sarahdayan** [comment]
@scotttrinh Just noticed your PR 👍 Will review when I get a chance.
