### ISSUE TITLE
Formatting bug in IE11 with Swedish locale sv-SE

### ISSUE THREAD

**Issue by joacim-boive** [sarahdayan/dinero.js#28]
## Expected behavior
GIVEN IE11 with English language
AND locale sv-SE
AND currency SEK
WHEN formatting 9999999
THEN result should be 99 999,99 kr

## Actual behavior
Format is 99.999,99 kr (note the ".")

## Steps to reproduce
https://codepen.io/joacim-boive/pen/QBRGxo/

This seems to be a bug in IE11 and it works if you run Windows in the Swedish language (witch is not as common as you might think).
https://github.com/MicrosoftDocs/visualstudio-docs/issues/629

But I think that bug could be addressed with in this library as it's affected.

**Comment by sarahdayan** [comment]
Hi @joacim-boive and sorry for the delay in replying.

This bug is inherent to the usage of `Number.prototype.toLocaleString` under the hood of the `toFormat` method. Unfortunately, the format varies depending on the implementation of `toLocaleString` of the end user's browser. This isn't something you or I can control.

I documented it just now: https://sarahdayan.github.io/dinero.js/module-Dinero.html#~toFormat

If you need strict formatting in every environment, you'll need to build your own helper.

I may look into a more robust solution in v2 but for now, I'm closing this.
