### ISSUE TITLE
Currency Parsing

### ISSUE THREAD

**Issue by osdiab** [sarahdayan/dinero.js#34]
I’d like to be able to parse currencies typed by the user, taking into account different internationalization formats like the German currency format. This handles formatting well but the opposite direction would be really nice!

**Comment by osdiab** [comment]
Given a user-inputted string representing a currency value, when a dinero.parseCurrency function is called on that input, then a dinero object representing that currency value is created.

So for example I type in “$5.00” in some application in my USA locale, I want a dinero object with that value. Similarly someone in Germany types “2.500,00 $” (is that how that works?), I want a dinero object correctly parsing that value, too.

**Comment by sarahdayan** [comment]
Hm I see. It would be a cool feature but just like `toFormat`, would have to rely on the Internationalization API. Because this has different implementations depending on browsers or environments, I'm hesitant to wrap it into a dedicated Dinero method (which would become untestable). That's why I'm considering [moving away from the Intl API for formatting](https://github.com/sarahdayan/dinero.js/issues/36).

Monetary format detection is hard, would add a heavy load of code, and I'm not sure it should be Dinero's responsibility.

Closing this for now.

**Comment by hamiltop** [comment]
I think saying "This is not Dinero's responsibility" is fine, but the Readme seems to communicate the opposite:
```
Dinero.js makes it easy to create, calculate and format monetary values in JavaScript. You can perform arithmetic operations, extensively *parse* and format them, check for a number of things to make your own development process easier and safer.
```
(emphasis mine)

Maybe we can update the Readme to not include parsing? I definitely came to this library because I saw it would do parsing in the Readme.

**Comment by agonbina** [comment]
Agreed with @hamiltop, parsing is a requirement for my use case and if I had not known the library is not able to parse "any kind of currency like values" I would have not taken the time to install it and go through the API documentation.

**Comment by orlandocr** [comment]
For the "parse" use case, what did you end up using? @osdiab @hamiltop @agonbina ?

**Comment by osdiab** [comment]
I ended up just designing the text inputs that people are allowed to type numbers in to disallow user-inputted formatting, and applies formatting itself. that way no need for flexible parsing

**Comment by christopherreay** [comment]
What would the Author of the library recommend as a way to achieve this?
