### ISSUE TITLE
Question: Is it possible to output a string using toFormat that looks like 'USD 1450.00'

### ISSUE THREAD

**Issue by ericlewis** [sarahdayan/dinero.js#37]
We are not entirely sure how the format method works, but doesn't seem to be possible for us to add a space `USD 0.0` seems to return `0.0` not what we would expect.

**Comment by ericlewis** [comment]
sorry for the not so great issue, im happy to discuss if you DM me on twitter: @ericlewis

**Comment by sarahdayan** [comment]
Hey Eric! What does your code look like? You should be able to get this by doing:

```
Dinero({ amount: 5050, currency: 'USD' }).toFormat('USD0,0.0')
```

As stated in the [docs](https://sarahdayan.github.io/dinero.js/module-Dinero.html#~toFormat), the string you pass to `toFormat` is a mask, because the methods wraps around `Number.prototype.toLocaleString`. You don't have exact control over how the string renders, this is automatically outputted depending on the locale of your Dinero object (to make it compliant with how currencies should be represented in that language).

Also, because `Number.prototype.toLocaleString` isn't stable, the format may slightly vary depending on how it's implemented in the end user's environment.

This is something I want to address in v2 so Dinero offers more control over how to format objects.
