### ISSUE TITLE
Wrong locale formatting on server side rendering

### ISSUE THREAD

**Issue by lucasfeliciano** [sarahdayan/dinero.js#65]
**Describe the bug**

When running `.toFormat()` on node seems like it doesn't take in consideration the locale set by `.setLocale()` or  `Dinero.globalLocale`, instead, the output is always `en_US` format.

Once the server-side rendering is done and javascript is initialized then dinero format the currency with the right locale.

**To reproduce**

https://runkit.com/lucasfeliciano/5cbb77911aa16300126723ab

**Expected behavior**

The expected output is `€ 3,00`

**Screenshots**

![image](https://user-images.githubusercontent.com/968014/56720936-22c0ab80-6744-11e9-9306-a03fad079b75.png)

**Node**

- v10.15.3

**Comment by davguij** [comment]
After some head scratching, just found the same bug.

**Comment by davguij** [comment]
I dug a little bit deeper... After a few tests I realised that the native `Intl.NumberFormat` method also gives the wrong output.

Turns out Node.js has just a few locales "embedded" by default.

Running `npm install full-icu` and then starting the `node` process with the `--icu-data-dir=node_modules/full-icu` flag (also possible to pass it as an env var) fixed it: after those steps, the output is correctly localised.

There's a short but super useful explanation here: https://stackoverflow.com/a/55183777/2982954

**Comment by sarahdayan** [comment]
Hi @lucasfeliciano and @davguij, and sorry for the long time replying.

Indeed, as the docs explain, the [toFormat](https://sarahdayan.github.io/dinero.js/module-Dinero.html#~toFormat) method wraps around `Number.prototype.toLocaleString`. For that reason, format will vary depending on how it's implemented in the end user's environment.

If you're using Dinero with Node, ensure you can build it with[ full-icu support](https://nodejs.org/api/intl.html#intl_embed_the_entire_icu_full_icu).
