### ISSUE TITLE
Is it possible to override the currency symbol toFormat uses for a particular currency?

### ISSUE THREAD

**Issue by thekevinbrown** [sarahdayan/dinero.js#69]
**Is your feature request related to a problem? Please describe.**

For example: 

```
const a = Dinero({ amount: 1000, currency: 'AUD' });
console.log(a.toFormat('$0.00'));

-> "A$10.00"
```

Our app is entirely based in Australia though, and here we don't really write 'A$' everywhere, we just write '$', then for US Dollars we write USD, so we'd expect 10 AUD to be written as `$10.00` and 10 USD to be written as `USD 10.00`, or `$10.00 USD`.

**Describe the solution you'd like**

I'd like to be able to configure Dinerojs so that it outputs AUD amounts as $ and USD amounts as USD instead of $.

**Describe alternatives you've considered**

As right now we only have one currency in the app so I'm just doing this:

```
Total: ${amount.toFormat('0.00')}
```

but I can see how this wouldn't be a scalable approach. I couldn't find much about this in the docs, is there something I can do to configure this?

**Comment by sarahdayan** [comment]
Hey @thekevinbrown, this is a design flaw of the current version which will be fixed in v2. You can read more about it [here](https://github.com/dinerojs/rfcs/blob/feat/v2/0001-dinerojs-v2.md#current-design-flaws), but in a nutshell, the native Internationalization API that Dinero is using under the hood when you call `toFormat` is the problem.

When using Australian dollars and trying to output them with their symbol, the Intl API considers that it should be written "A$", which I understand doesn't necessarily make sense.

The Intl API probably bases itself on a formal notation that doesn't reflect how people actually write it. **That's part of the reason why I'm ditching it in v2.**

For now, the only option I see is to write your own wrapper.

```js
function toFormatAUD(d) {
  return `$ ${d.toFormat('0.00')}`
}

// or

function toFormat(d) {
  return d.getCurrency() === 'AUD' ? `$ ${d.toFormat('0.00')}` : d.toFormat('$0.00')
}
```

This is less than ideal, I understand it. Unfortunately, until v2 comes out, this will be necessary.
