### ISSUE TITLE
Defaults constant did not specify in typescript

### ISSUE THREAD

**Issue by lokingwei** [sarahdayan/dinero.js#70]
**Describe the bug**
defaultAmount, defaultCurrency and defaultPrecision did not specify in typescript lead to typescript error

`TS2339: Property 'defaultCurrency' does not exist on type 'typeof DineroFactory'.`

**To reproduce**
1. create a typescript project
2. install dinero.js
3. use the default object and overwrrite default constant
4. typescipt compile

**Expected behavior**
Typechecking pass

**Screenshots**
![image](https://user-images.githubusercontent.com/10398988/61992220-f9d6ec00-b08d-11e9-8c78-5eca95a4aaef.png)

**Comment by thekevinbrown** [comment]
The typescript definitions are not on this repository, they're in DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/dinero.js/index.d.ts

This issue is probably better raised over there, or actually it's a pretty simple change, so a quick way to resolve this is to just do a PR on that file to meet your needs.
