### ISSUE TITLE
v2 Release Plans

### ISSUE THREAD

**Issue by thekevinbrown** [sarahdayan/dinero.js#75]
Hi there,

Back in September I asked about #69 and the resolution was to wait for v2. I'm wondering what the status of v2 is, when it's expected to be released, and if there's anything I can do to help.

Thanks!

**Comment by sarahdayan** [comment]
Hi @thekevinbrown, I'm currently starting back to actively work on v2. I expect to get it out end of Q1 2020.

Thanks for offering your help! What would be very helpful would be to look at the current issues that aren't marked as enhancements and give me a hand with them :)

Closing this for now since this isn't an issue, but don't hesitate to ping me on Twitter for status.

**Comment by thekevinbrown** [comment]
Hey @sarahdayan, just wanted to let you know I think I've fixed the remaining outstanding bug in #77.

**Comment by sarahdayan** [comment]
Thank you, will review soon :)
