### ISSUE TITLE
Rounding wrong after multiplication

### ISSUE THREAD

**Issue by magnusjt** [sarahdayan/dinero.js#8]
Dinero({amount: 209050}).multiply(8.62).toRoundedUnit(2) // 18020.11 (expected 18020.11) (correct)
Dinero({amount: 209050}).multiply(8.61).toRoundedUnit(2) // 17999.2   (expected 17999.21) (wrong)

**Comment by tarnelope** [comment]
I'm happy to work on this too. I think @scotttrinh 's https://github.com/sarahdayan/dinero.js/pull/12 will address multiplication with float in the example so I'll wait until he's PR is merged first.

**Comment by sarahdayan** [comment]
@magnusjt @tarnelope This issue is about transforming float factors into integers then dividing them back, but it will not change the result for this specific case.

What happens right now is that the multiplication gives us inaccurate results. `209050 * 8.61` returns `1799920.4999999998`, typical floating point math. The result is rounded so it ends up being `1799920`. Finally, it's formatted to unit with two decimal places, meaning `17999,20` or `17999,2`.

If we fix it by doing `209050 * 861 / 100`, we'll get `1799920.5`, which will be rounded using Banker's rounding (since #11), and end up as `1799920`.

The multiplication (and division) algorithms should absolutely be fixed, but won't result in the expected result from this issue.

**Comment by sarahdayan** [comment]
Fixed in [v1.0.4](https://github.com/sarahdayan/dinero.js/releases/tag/v1.0.4)
